basePath: /
host: localhost:8000
info:
  contact: {}
  description: This is a sample server for a API.
  title: My Api Service
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
